//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.10.18 at 11:00:53 AM CDT 
//


package com.itq.aguaService.dto;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.itq.autoService.dto package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.itq.autoService.dto
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link NewCliente }
     * 
     */
    public NewCliente createNewCliente() {
        return new NewCliente();
    }

    /**
     * Create an instance of {@link Cliente }
     * 
     */
    public Cliente createCliente() {
        return new Cliente();
    }

    /**
     * Create an instance of {@link ClienteId }
     * 
     */
    public ClienteId createClienteId() {
        return new ClienteId();
    }

    /**
     * Create an instance of {@link ClienteIdDelete }
     * 
     */
    public ClienteIdDelete createClienteIdDelete() {
        return new ClienteIdDelete();
    }

    /**
     * Create an instance of {@link NewCliente.Direccion }
     * 
     */
    public NewCliente.Direccion createNewClienteDireccion() {
        return new NewCliente.Direccion();
    }

    /**
     * Create an instance of {@link Cliente.Direccion }
     * 
     */
    public Cliente.Direccion createClienteDireccion() {
        return new Cliente.Direccion();
    }

    /**
     * Create an instance of {@link Ack }
     * 
     */
    public Ack createAck() {
        return new Ack();
    }

    /**
     * Create an instance of {@link NewSolicitud }
     * 
     */
    public NewSolicitud createNewSolicitud() {
        return new NewSolicitud();
    }

    /**
     * Create an instance of {@link SolicitudID }
     * 
     */
    public SolicitudID createSolicitudID() {
        return new SolicitudID();
    }

    /**
     * Create an instance of {@link SolicitudIDDelete }
     * 
     */
    public SolicitudIDDelete createSolicitudIDDelete() {
        return new SolicitudIDDelete();
    }

    /**
     * Create an instance of {@link Solicitud }
     * 
     */
    public Solicitud createSolicitud() {
        return new Solicitud();
    }

    /**
     * Create an instance of {@link TanqueID }
     * 
     */
    public TanqueID createTanqueID() {
        return new TanqueID();
    }

    /**
     * Create an instance of {@link TanqueIDDelete }
     * 
     */
    public TanqueIDDelete createTanqueIDDelete() {
        return new TanqueIDDelete();
    }

    /**
     * Create an instance of {@link NewTanque }
     * 
     */
    public NewTanque createNewTanque() {
        return new NewTanque();
    }

    /**
     * Create an instance of {@link Tanque }
     * 
     */
    public Tanque createTanque() {
        return new Tanque();
    }

}
